version: "3.8"

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=500"]
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  web:
    build: .
    command: "./bin/rails server"
    volumes:
      - ./log:/rails/log
      - app-storage:/rails/storage
    secrets:
      - source: master_key
        target: /rails/config/master.key
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - CLOUDINARY_API_URL=${CLOUDINARY_API_URL}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    depends_on:
      - db
    ports:
      - "3000:3000"

secrets:
  master_key:
    file: ./config/master.key

volumes:
  postgres_data:
  app-storage:
